[platformio]
name = HydroDozerPump
default_envs = WEMOS_D1_Mini
src_dir = src/HydroDozerPump

[env:WEMOS_D1_Mini]
platform = espressif8266
board = d1_mini
framework = arduino

monitor_speed = 115200
upload_speed = 115200     ; safer than 460800 on many USB cables
custom_fw_version_base = 3.0
extra_scripts = pre:scripts/bump_version.py

; ---- Flash Layout (VERY important for OTA) ----
board_build.ldscript = eagle.flash.4m2m.ld
board_build.filesystem = littlefs

; ---- Build Flags ----
build_flags =
    -DCORE_DEBUG_LEVEL=0     ; reduce serial noise
    -DNDEBUG                ; saves RAM
    -DMQTT_MAX_PACKET_SIZE=1024

; ---- Libraries ----
lib_deps =
    tzapu/WiFiManager@^2.0.17
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^6.21.5
    ayushsharma82/ElegantOTA@^2.2.9
